Repository miticc06/karaoke-frontend, pull requests merged in 2019-12, with the labels that each got.

#66 Tien add page payment
  src/views/Payment/index.js
  src/views/Payment/query.js
  src/views/Payment/style.less
Labels: merge when green

#67 load details bill
  package.json
  src/views/Payment/columnsTable.js
  src/views/Payment/index.js
  src/views/Payment/style.less
Labels: merge when green

#68 Tien add page payment
  src/views/Payment/columnsTable.js
  src/views/Payment/index.js
  src/views/Payment/query.js
  src/views/Payment/style.less
Labels: merge when green

#69 Add service in bill
  src/views/Payment/index.js
  src/views/Payment/query.js
  src/views/Payment/style.less
Labels: merge when green

#70 Update manage ticket
  package.json
  src/views/Payment/index.js
  src/views/Tickets/ModalAddTicket.js
  src/views/Tickets/ModalEditTicket.js
  src/views/Tickets/index.js
Labels: merge when green

#71 Fix bug build project
  .travis.yml
  package.json
  src/views/Discounts/ModalAddDiscount.js
  src/views/Discounts/ModalEditDiscount.js
  src/views/Discounts/index.js
  src/views/Payment/columnsTable.js
  src/views/Payment/index.js
  src/views/Payment/query.js
  src/views/Payment/style.less
  src/views/Tickets/ModalAddTicket.js
Labels: merge when green

#74 Tien add page payment
  src/views/Payment/ModalChangeEndTimeService.js
  src/views/Payment/ModalChangeRoom.js
  src/views/Payment/ModalPay.js
  src/views/Payment/columnsTable.js
  src/views/Payment/index.js
  src/views/Payment/query.js
  src/views/Payment/style.less
Labels: merge when green

#76 Tien fix build
  .eslintrc
  .gitignore
  package.json
  yarn.lock
Labels: Bugs, merge when green

#81 fixed package + pay bill
  .eslintrc
  package.json
  src/views/Payment/ModalChangeRoom.js
  src/views/Payment/ModalPay.js
  src/views/Payment/columnsTableModalPay.js
  src/views/Payment/index.js
  src/views/Payment/query.js
Labels: Bugs, merge when green

#85 Tien pay
  src/views/Bill/ModalViewBill.js
  src/views/Bill/index.js
  src/views/Bill/query.js
  src/views/Payment/ModalChangeEndTimeService.js
  src/views/Payment/ModalChangeRoom.js
  src/views/Payment/ModalPay.js
  src/views/Payment/index.js
  src/views/Payment/query.js
  src/views/Rooms/ModalEditRoom.js
  src/views/Services/ModalEditService.js
  src/views/Users/index.js
Labels: merge when green

#88 Tien fix 87
  src/views/Payment/index.js
Labels: merge when green

#92 Tien report
  src/Routes.js
  src/layouts/Main/components/Sidebar/Sidebar.js
  src/views/Report/columnsdefs.js
  src/views/Report/index.js
  src/views/Report/query.js
  src/views/Report/style.less
  src/views/index.js
Labels: merge when green

#93 add report
  src/views/Report/columnsdefs.js
  src/views/Report/index.js
  src/views/Report/query.js
Labels: merge when green

#95 done report
  src/views/Report/index.js
Labels: merge when green

#96 product
  src/views/Report/index.js
Labels: merge when green

#98 Luan fix payment
  package.json
  src/views/Bill/ModalViewBill.js
  src/views/Bill/index.js
  src/views/Discounts/ModalAddDiscount.js
  src/views/Discounts/ModalEditDiscount.js
  src/views/Discounts/TimePicker.js
  src/views/Discounts/index.js
  src/views/Payment/ModalPay.js
  src/views/Payment/billExport.js
  src/views/Payment/index.js
  src/views/Payment/query.js
  yarn.lock
Labels: merge when green

#99 product
  package.json
  public/index.html
  src/views/Bill/ModalViewBill.js
  src/views/Bill/index.js
  src/views/Dashboard/Dashboard.js
  src/views/Dashboard/components/Budget/Budget.js
  src/views/Dashboard/components/LatestOrders/LatestOrders.js
  src/views/Dashboard/components/LatestOrders/data.js
  src/views/Dashboard/components/LatestProducts/LatestProducts.js
  src/views/Dashboard/components/LatestSales/LatestSales.js
  src/views/Dashboard/components/TasksProgress/TasksProgress.js
  src/views/Dashboard/components/TotalProfit/TotalProfit.js
  src/views/Dashboard/components/TotalUsers/TotalUsers.js
  src/views/Dashboard/components/UsersByDevice/UsersByDevice.js
  src/views/Discounts/ModalAddDiscount.js
  src/views/Discounts/ModalEditDiscount.js
  src/views/Discounts/TimePicker.js
  src/views/Discounts/index.js
  src/views/Payment/ModalPay.js
  src/views/Payment/billExport.js
  src/views/Payment/index.js
  src/views/Payment/query.js
  yarn.lock
Labels: merge when green

#101 Config cypress
  .eslintignore
  .gitignore
  .travis.yml
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/module0/login.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package.json
  yarn.lock
Labels: merge when green

#104 Fix bug modalpay
  .travis.yml
  src/views/Payment/ModalPay.js
Labels: merge when green

#105 Update cicd
  .travis.yml
Labels: merge when green

#112 deploy product
  .gitignore
  .travis.yml
  cypress.json
  deploy_rsa.enc
  src/views/Bill/ModalViewBill.js
  src/views/Bill/index.js
  src/views/Bill/query.js
  src/views/Payment/ModalPay.js
  src/views/Payment/billExport.js
Labels: merge when green

#113 Tien test module9
  cypress/integration/module9/1.add-user.spec.js
  cypress/integration/module9/2.list-user.spec.js
  src/views/Dashboard/Dashboard.js
  src/views/Dashboard/components/LatestOrders/LatestOrders.js
  src/views/Discounts/ModalAddDiscount.js
  src/views/Discounts/ModalEditDiscount.js
  src/views/Discounts/TimePicker.js
  src/views/Payment/billExport.js
  src/views/Report/columnsdefs.js
  src/views/Report/index.js
Labels: Test, merge when green

#115 Update test module 9
  cypress/integration/module9/3.edit-user.spec.js
  src/views/Users/index.js
Labels: Test, merge when green

#116 Deploy product
  cypress/integration/module9/1.add-user.spec.js
  cypress/integration/module9/2.list-user.spec.js
  cypress/integration/module9/3.edit-user.spec.js
  src/views/Dashboard/Dashboard.js
  src/views/Dashboard/components/LatestOrders/LatestOrders.js
  src/views/Discounts/ModalAddDiscount.js
  src/views/Discounts/ModalEditDiscount.js
  src/views/Discounts/TimePicker.js
  src/views/Payment/billExport.js
  src/views/Report/columnsdefs.js
  src/views/Report/index.js
  src/views/Users/index.js
Labels: Test, merge when green

#117 Add test module 5
  cypress/integration/module5/1.add-room.spec.js
  cypress/integration/module5/2.edit-room.spec.js
  cypress/integration/module5/3.list-room.spec.js
  cypress/integration/module5/4.delete-room.spec.js
  cypress/integration/module9/1.add-user.spec.js
  src/views/Rooms/index.js
Labels: merge when green

#119 deploy product
  cypress/integration/module5/1.add-room.spec.js
  cypress/integration/module5/2.edit-room.spec.js
  cypress/integration/module5/3.list-room.spec.js
  cypress/integration/module5/4.delete-room.spec.js
  cypress/integration/module9/1.add-user.spec.js
  src/views/Rooms/index.js
Labels: Test, merge when green
